"""界面控制抽象接口：命令实现与渲染框架解耦的唯一通道。"""

from typing import Protocol

from endless_code.command.types import (
    ModelOption,
    SessionInfo,
    StyleOption,
    SwitchResult,
)
from endless_code.permission import Mode


class CommandHost(Protocol):
    """命令实现可用的全部界面能力；由终端界面实现。"""

    # 输出
    def show_notice(self, text: str) -> None: ...
    def show_error(self, text: str) -> None: ...

    # 对话流
    def send_user_message(self, text: str) -> None: ...
    def get_last_error(self) -> str: ...
    def get_last_reply(self) -> str: ...

    # 权限模式
    def get_mode(self) -> Mode: ...
    def set_mode(self, mode: Mode) -> None: ...

    # 模型与输出样式
    def get_model_options(self) -> list[ModelOption]: ...
    def switch_model(self, selector: str) -> SwitchResult: ...
    def get_style_options(self) -> list[StyleOption]: ...
    def set_output_style(self, name: str) -> SwitchResult: ...

    # 状态与记忆
    def get_session_info(self) -> SessionInfo: ...
    def get_memory_index(self) -> str: ...
    def show_audit(self) -> None: ...

    # 会话与流程
    def start_compact(self) -> None: ...
    def start_resume(self) -> None: ...
    def enter_plan(self) -> None: ...
    def start_execute(self) -> None: ...
    def clear_session(self) -> None: ...
    def quit_app(self) -> None: ...

    # checkpoint 回滚
    def start_rewind(self) -> None: ...
    def rewind_available(self) -> bool: ...
    def get_checkpoint_mode(self) -> str: ...
