"""上下文管理的固定阈值。"""

RECOVERY_FILE_LIMIT = 5
RECENT_KEEP_MESSAGES = 5
MAX_CONSECUTIVE_AUTO_COMPACT_FAILURES = 3
PTL_RETRY_LIMIT = 3
PTL_DROP_PERCENTAGE = 0.2
ESTIMATE_CHARS_PER_TOKEN = 3.5
PREVIEW_HEAD_BYTES = 2_048
PREVIEW_HEAD_LINES = 20
